templates baby

diff --git a/Dockerfile.j2 b/Dockerfile.j2
--- a/Dockerfile.j2
+++ b/Dockerfile.j2
@@ -13,10 +13,10 @@ ENV AWS_SECRET_ACCESS_KEY={{aws_key}}
 RUN apt-get install -y vim
 
 ## run tests
-RUN ansible-playbook -vvvv -i "[test] localhost," -c local -e "environ=dev" tests.yml #&&\
-    #ansible-playbook -i "[test] localhost," -c local -e "environ=dev" tests.yml 2>/dev/null | grep -q 'changed=0.*failed=0' &&\
-    #(echo 'Idempotence test: \033[0;32mpass\033[0m' && exit 0) ||\
-    #(echo 'Idempotence test: \033[0;31mfail\033[0m' && exit 1)
+RUN ansible-playbook -vvvv -i "[test] localhost," -c local -e "environ=dev" tests.yml &&\
+    ansible-playbook -i "[test] localhost," -c local -e "environ=dev" tests.yml 2>/dev/null | grep -q 'changed=0.*failed=0' &&\
+    (echo 'Idempotence test: \033[0;32mpass\033[0m' && exit 0) ||\
+    (echo 'Idempotence test: \033[0;31mfail\033[0m' && exit 1)
 
 EXPOSE 8080
 
